### ISSUE TITLE
`charge` method in `ChargeClient` is sending wrong payload

### ISSUE THREAD

**Issue by Smahrt** [gray-adeyi/paystack-sdk#48]
I was trying to initiate a charge with a reusable `authorization_code` and the param in the error message shows the SDK is sending `auth_code` instead of `authorization_code` in the param. 

```ts
paystack.charge.charge({ authCode, reference, amount, email });
```

```json
{
        "detail": "Request failed with status code 400",
        "status": 400,
        "code": "ERR_BAD_REQUEST",
        "wrappedError": {
            "message": "Request failed with status code 400",
            "name": "AxiosError",
            "stack": "AxiosError: Request failed with status code 400\n    at settle (file:///Users/user/Projects/wonderads-api/node_modules/axios/lib/core/settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (file:///Users/user/Projects/wonderads-api/node_modules/axios/lib/adapters/http.js:599:11)\n    at IncomingMessage.emit (node:events:530:35)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)",
            "config": {
                "transitional": {
                    "silentJSONParsing": true,
                    "forcedJSONParsing": true,
                    "clarifyTimeoutError": false
                },
                "adapter": [
                    "xhr",
                    "http",
                    "fetch"
                ],
                "transformRequest": [
                    null
                ],
                "transformResponse": [
                    null
                ],
                "timeout": 0,
                "xsrfCookieName": "XSRF-TOKEN",
                "xsrfHeaderName": "X-XSRF-TOKEN",
                "maxContentLength": -1,
                "maxBodyLength": -1,
                "env": {},
                "headers": {
                    "Accept": "application/json",
                    "Content-Type": "application/json",
                    "User-Agent": "@gray-adeyi/paystack-sdk 0.1.4",
                    "Authorization": "Bearer sk_test_ef7eac3fb*****d74475c******d1f56e0a*****",
                    "Content-Length": "99",
                    "Accept-Encoding": "gzip, compress, deflate, br"
                },
                "baseURL": "https://api.paystack.co",
                "method": "post",
                "url": "/charge",
                "data": "{\"auth_code\":\"AUTH_uuzdlhmz3a\",\"reference\":\"rtbub7gmt0\",\"amount\":10000,\"email\":\"someone@gmail.com\"}"
            },
            "code": "ERR_BAD_REQUEST",
            "status": 400
        }
```

**Comment by gray-adeyi** [comment]
Hi @Smahrt your error dump seems to be incomplete. Please update to the latest version of the package `0.1.4`. the `authCode` parameter should be passed in as `authorizationCode`. Let me know if the issue persists

**Comment by Smahrt** [comment]
version `0.1.5` fixed it. Thanks.

**Comment by gray-adeyi** [comment]
@Smahrt please don't forget to give the project a star and share with your developer friends if you find it useful. You should also try out the cli in the documentation. Happy coding 🥳

**Comment by Smahrt** [comment]
Sure thing. I'd love to contribute within the coming week. You have an nice project on your hands.

**Comment by gray-adeyi** [comment]
Hi @Smahrt @gray-adeyi/paystack-sdk 0.2.4 release is now available with even better type support 🔥 https://www.npmjs.com/package/@gray-adeyi/paystack-sdk
